version: '3.9'

services:
  web:
    build:
      context: ./geodjango
    command: sh -c "python manage.py migrate && gunicorn geodjango.wsgi:application --bind 0.0.0.0:8000"
    #command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    restart: always
    expose:
      - 8000
    # ports:
    #   - 8000:8000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16.4
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=geodjango_db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=P@55w0rd
    env_file:
      - ./.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${SQL_DATABASE} -U $${SQL_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.27.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  db_data:
  static_volume:
  media_volume: